name: run main.py
#/media/boris/0E471A3B0E471A3B/F/Projects archive - for Github/Python/PythonAutomation/main.py
#on:
#  schedule:
#    # schedule the script to run every 2 hours
#    - cron: "* * * * *" python ~home/runner/work/PythonAutomation/main.py

on:
  push:

  schedule:
    - cron: '* * * * *'
    # script to run every minute?
    #-cron: '* * * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: python setup
        uses: actions/setup-python@v4
        with:
          # install the python version required
          python-version: '3.9'

      - name: install python packages
        # using run to run multiple lines in command line
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt


      - name: execute python script
        run: python3 main.py

      - name: commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -A
            git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          # if this works it is done manually, I haven't declared the variable GITHUB_TOKEN!
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
